export const APP_ERROR_CODES = {
  VALIDATION_ERROR: "VALIDATION_ERROR",
  AUTH_REQUIRED: "AUTH_REQUIRED",
  INVALID_CREDENTIALS: "INVALID_CREDENTIALS",
  PRODUCT_NOT_FOUND: "PRODUCT_NOT_FOUND",
  ORDER_NOT_FOUND: "ORDER_NOT_FOUND",
  IDEMPOTENCY_KEY_REQUIRED: "IDEMPOTENCY_KEY_REQUIRED",
  DUPLICATE_ORDER_CONFLICT: "DUPLICATE_ORDER_CONFLICT",
  STOCK_INSUFFICIENT: "STOCK_INSUFFICIENT",
  ERP_TEMPORARY_FAILURE: "ERP_TEMPORARY_FAILURE",
  INTERNAL_ERROR: "INTERNAL_ERROR"
} as const;

export type AppErrorCode =
  (typeof APP_ERROR_CODES)[keyof typeof APP_ERROR_CODES];
